FROM python:3

ADD requirements.txt /
RUN pip3 install -r /requirements.txt; \
    export DEBIAN_FRONTEND=noninteractive; \
    apt-get update; \
    apt-get install -y build-essential xorg gdebi; \
    apt-get -y install ruby; \
    gem install kramdown; \
    wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz; \
    tar xf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz; \
    mv wkhtmltox/bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf; \
    chmod +x /usr/local/bin/wkhtmltopdf;

ENV PYTHONUNBUFFERED=1
CMD ["python3", "/code/kotlin-website.py"]